# Generated by Django 4.1.2 on 2022-10-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='book2',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
