# Generated by Django 4.1.2 on 2022-10-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_book1_user_book2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book1', models.CharField(default=0, max_length=100)),
                ('book2', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='book1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='book2',
        ),
    ]
