# Generated by Django 4.1.2 on 2022-10-13 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_book1_cart_book_remove_cart_book2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='book',
            new_name='book1',
        ),
        migrations.AddField(
            model_name='cart',
            name='book2',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
