# Generated by Django 4.1.2 on 2022-10-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_book_cart_book1_cart_book2_alter_cart_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='book1',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='book2',
        ),
        migrations.AddField(
            model_name='user',
            name='book1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='book2',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
