# Generated by Django 4.1.2 on 2022-10-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_cart_book1_remove_cart_book2_user_book1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book1',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='book2',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
