# Generated by Django 4.1.2 on 2022-10-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverpage',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
