# Generated by Django 4.1.2 on 2022-10-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_book_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed',
        ),
    ]
