# Generated by Django 4.1.2 on 2022-10-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_book_year_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='timestamp',
            new_name='added_date',
        ),
    ]
