# Generated by Django 4.1.2 on 2022-12-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
